# Generated by Django 4.1.5 on 2023-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='percent',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
