# Generated by Django 4.1.7 on 2023-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_question_options_alter_userresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], help_text='گزینه درست را انتخاب کنید', max_length=7, verbose_name='پاسخ'),
        ),
    ]
