services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9
    networks:
      - main
    ports:
      - "5672:5672"
    restart: always

  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    container_name: quizApp
    volumes:
      - .:/source/
    expose:
      - "8000"
    networks:
      - main
    depends_on:
      - rabbitmq
    restart: always

  celery_worker:
    container_name: celery_worker
    command: "celery -A QuizApp worker -l INFO"
    depends_on:
      - rabbitmq
      - app
    build: .
    environment:
      - C_FORCE_ROOT="true"
      - CELERY_BROKER_URL=amqp://guest@rabbitmq:5672//
    networks:
      - main
    restart: always


  flower_worker:
    container_name: flower_worker
    command: "celery -A QuizApp --broker=amqp://guest@rabbitmq:5672// flower"
    depends_on:
      - celery_worker
      - app
      - rabbitmq
    build: .
    ports:
      - 5555:5555
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:1.25
    networks:
      - main
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static

networks:
  main: